version: '3'
services:
  web:
    image: madhusoodanreddy/dockerweb-web:v1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1234    
      mysqli_ROOT_PASSWORD: 1234
      mysqli_DATABASE: users
      mysqli_USER: users
      mysqli_PASSWORD: 1234
    volumes:
      - ./mydb.sql:/docker-entrypoint-initdb.d/mydb.sql
      